In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


Two Types of Tensors:


1.   Constant
2.   Variable



***tf.constant()***
<br>Tensors created in this way are immutable

In [2]:
ta = tf.constant(49)
ta

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [3]:
ta.shape

TensorShape([])

In [4]:
ta.dtype

tf.int32

In [5]:
tb = tf.constant([[2.,5.],[9.,4.]])
tb

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [9., 4.]], dtype=float32)>

In [6]:
tb.shape

TensorShape([2, 2])

In [7]:
tb.dtype

tf.float32

**Subsetting tensor**

In [8]:
tb

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [9., 4.]], dtype=float32)>

In [9]:
tb[:,1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 4.], dtype=float32)>

In [10]:
tb[0,:]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

**Mathematical Operations**

In [11]:
ta+4

<tf.Tensor: shape=(), dtype=int32, numpy=53>

In [12]:
tb

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [9., 4.]], dtype=float32)>

In [13]:
tf.transpose(tb)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 9.],
       [5., 4.]], dtype=float32)>

Matrix Multiplication

In [ ]:
tc = tf.constant([[3.,4.],[7.,9.],[0.,2.]])
tc

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [7., 9.],
       [0., 2.]], dtype=float32)>

In [ ]:
tc @ tb

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[42., 31.],
       [95., 71.],
       [18.,  8.]], dtype=float32)>

Calculations

In [ ]:
tf.reduce_sum(tc)

<tf.Tensor: shape=(), dtype=float32, numpy=25.0>

In [ ]:
tf.reduce_mean(tc)

<tf.Tensor: shape=(), dtype=float32, numpy=4.166666507720947>

In [ ]:
tf.reduce_max(tc)

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

Some Maths

In [ ]:
tf.math.log(tc)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.0986123, 1.3862944],
       [1.9459102, 2.1972246],
       [     -inf, 0.6931472]], dtype=float32)>

In [ ]:
tf.math.exp(tc)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2.0085537e+01, 5.4598148e+01],
       [1.0966332e+03, 8.1030840e+03],
       [1.0000000e+00, 7.3890562e+00]], dtype=float32)>

**Type Conversions**

In [ ]:
ta

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [ ]:
td = tf.constant(57.4)
td

<tf.Tensor: shape=(), dtype=float32, numpy=57.400001525878906>

In [ ]:
ta + td

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

In [ ]:
td +  tf.cast(ta, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=106.4000015258789>

***tf.Variable()***
<BR>Variables created in this way, are mutable and can be used to implement weights in neural networks

In [ ]:
va = tf.Variable([[22.,35.,59.],[45.,98.,23.]])
va

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[22., 35., 59.],
       [45., 98., 23.]], dtype=float32)>

*tf.Variable* can perform same operations as *tf.Tensor* <BR>It has also some functions like *assign()*, *assign_add()* etc.

In [ ]:
va.assign(3*va)
va

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 66., 105., 177.],
       [135., 294.,  69.]], dtype=float32)>

Trying it with constant tensor

In [ ]:
tc = tf.constant([[3.,4.],[7.,9.],[0.,2.]])
tc

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [7., 9.],
       [0., 2.]], dtype=float32)>

In [ ]:
tc.assign(3*tc)
tc

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

###Custom Loop

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
x = np.linspace(-2,2, 20)
def f(x):
  return x * 3.0 + 5.0
y = f(x)

In [ ]:
initial_w = 0.1
initial_b = 0.3
class Model(tf.Module):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)
    # In practice, these should be randomly initialized
    self.w = tf.Variable(initial_w)
    self.b = tf.Variable(initial_b)

  def __call__(self, x):
    return self.w * x + self.b

model = Model()

In [ ]:
def loss(predicted_y, actual_y):
  return tf.reduce_mean(tf.square(predicted_y - actual_y))

x = tf.convert_to_tensor(x, dtype=tf.float32)
y = tf.convert_to_tensor(y, dtype=tf.float32)

In [ ]:
def train(model, inputs, outputs, learning_rate):
  with tf.GradientTape() as t:
    current_loss = loss(model(inputs),outputs)
  dw, db = t.gradient(current_loss, [model.w, model.b])
  model.w.assign_sub(learning_rate * dw)
  model.b.assign_sub(learning_rate * db)
  return current_loss;

In [ ]:
model = Model()

list_w = []
list_b = []
losses = []
for epoch in range(30):
  list_w.append(model.w.numpy())
  list_b.append(model.b.numpy())
  current_loss = train(model, x, y, learning_rate=0.1)
  losses.append(current_loss)
  print('Epoch %2d: w=%1.2f b=%1.2f, loss=%2.5f' % (epoch,model.w.numpy(),model.b.numpy(),current_loss))


Epoch  0: w=0.95 b=1.24, loss=34.48368
Epoch  1: w=1.56 b=1.99, loss=20.30217
Epoch  2: w=1.98 b=2.59, loss=12.11430
Epoch  3: w=2.28 b=3.07, loss=7.31589
Epoch  4: w=2.49 b=3.46, loss=4.46468
Epoch  5: w=2.64 b=3.77, loss=2.74922
Epoch  6: w=2.75 b=4.01, loss=1.70569
Epoch  7: w=2.82 b=4.21, loss=1.06488
Epoch  8: w=2.87 b=4.37, loss=0.66821
Epoch  9: w=2.91 b=4.50, loss=0.42103
Epoch 10: w=2.94 b=4.60, loss=0.26617
Epoch 11: w=2.96 b=4.68, loss=0.16871
Epoch 12: w=2.97 b=4.74, loss=0.10716
Epoch 13: w=2.98 b=4.79, loss=0.06818
Epoch 14: w=2.98 b=4.83, loss=0.04343
Epoch 15: w=2.99 b=4.87, loss=0.02770
Epoch 16: w=2.99 b=4.89, loss=0.01768
Epoch 17: w=2.99 b=4.92, loss=0.01129
Epoch 18: w=3.00 b=4.93, loss=0.00721
Epoch 19: w=3.00 b=4.95, loss=0.00461
Epoch 20: w=3.00 b=4.96, loss=0.00295
Epoch 21: w=3.00 b=4.97, loss=0.00188
Epoch 22: w=3.00 b=4.97, loss=0.00121
Epoch 23: w=3.00 b=4.98, loss=0.00077
Epoch 24: w=3.00 b=4.98, loss=0.00049
Epoch 25: w=3.00 b=4.99, loss=0.00032
Epoch 26:

In [ ]:
x = np.linspace(-2,2, 20)
def f(x):
  return x * 3.0 + 5.0
y = f(x)

In [ ]:
x.shape

(20,)

In [ ]:
x

array([-2.        , -1.78947368, -1.57894737, -1.36842105, -1.15789474,
       -0.94736842, -0.73684211, -0.52631579, -0.31578947, -0.10526316,
        0.10526316,  0.31578947,  0.52631579,  0.73684211,  0.94736842,
        1.15789474,  1.36842105,  1.57894737,  1.78947368,  2.        ])

In [ ]:
x = x.reshape(-1,1)
x.shape

(20, 1)

In [ ]:
x.shape[1]

1

#### Model Definition

In [14]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(x.shape[1],)),
    tf.keras.layers.Dense(1, kernel_initializer=tf.keras.initializers.LecunNormal(seed=25),
                          bias_initializer=tf.keras.initializers.Zeros())
])
print(model.summary())

NameError: name 'x' is not defined

In [ ]:
model.get_weights()

[array([[-0.6726856]], dtype=float32), array([0.], dtype=float32)]

In [ ]:
#model.compile(optimizer='sgd', loss='mean_squared_error',metrics=['mae'])

In [ ]:
#model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.5), loss='mean_squared_error',metrics=['mae'])

In [ ]:
#model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.5,nesterov=True),
# loss='mean_squared_error',metrics=['mae'])

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
  loss='mean_squared_error',metrics=['mae'])

In [ ]:
history = model.fit( x,y,verbose=2, epochs=100)

Epoch 1/100
1/1 - 1s - 669ms/step - loss: 42.8285 - mae: 5.3485
Epoch 2/100
1/1 - 0s - 38ms/step - loss: 42.6254 - mae: 5.3361
Epoch 3/100
1/1 - 0s - 55ms/step - loss: 42.4228 - mae: 5.3237
Epoch 4/100
1/1 - 0s - 56ms/step - loss: 42.2208 - mae: 5.3114
Epoch 5/100
1/1 - 0s - 36ms/step - loss: 42.0193 - mae: 5.2990
Epoch 6/100
1/1 - 0s - 56ms/step - loss: 41.8183 - mae: 5.2866
Epoch 7/100
1/1 - 0s - 61ms/step - loss: 41.6178 - mae: 5.2743
Epoch 8/100
1/1 - 0s - 57ms/step - loss: 41.4179 - mae: 5.2619
Epoch 9/100
1/1 - 0s - 36ms/step - loss: 41.2186 - mae: 5.2496
Epoch 10/100
1/1 - 0s - 36ms/step - loss: 41.0198 - mae: 5.2372
Epoch 11/100
1/1 - 0s - 37ms/step - loss: 40.8216 - mae: 5.2249
Epoch 12/100
1/1 - 0s - 58ms/step - loss: 40.6240 - mae: 5.2125
Epoch 13/100
1/1 - 0s - 38ms/step - loss: 40.4269 - mae: 5.2002
Epoch 14/100
1/1 - 0s - 58ms/step - loss: 40.2305 - mae: 5.1879
Epoch 15/100
1/1 - 0s - 59ms/step - loss: 40.0346 - mae: 5.1756
Epoch 16/100
1/1 - 0s - 55ms/step - loss: 39.839

In [ ]:
model.get_weights()

[array([[0.37526163]], dtype=float32), array([1.0629072], dtype=float32)]